### ISSUE TITLE
Tracking object_get_info pending scenarios

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/FuchsiaSharp#2]
- [ ] ZX_INFO_PROCESS_HANDLE_STATS
- [ ] ZX_INFO_PROCESS
- [ ] ZX_INFO_PROCESS_THREADS
- [ ] ZX_INFO_THREAD
- [ ] ZX_INFO_THREAD_EXCEPTION_REPORT
- [ ] ZX_INFO_THREAD_STATS
- [ ] ZX_INFO_CPU_STATS
- [ ] ZX_INFO_VMAR
- [ ] ZX_INFO_VMO
- [ ] ZX_INFO_SOCKET
- [ ] ZX_INFO_JOB_CHILDREN
- [ ] ZX_INFO_JOB_PROCESSES
- [ ] ZX_INFO_TASK_STATS
- [ ] ZX_INFO_PROCESS_MAPS
- [ ] ZX_INFO_PROCESS_VMOS
- [ ] ZX_INFO_KMEM_STATS
- [ ] ZX_INFO_RESOURCE
- [ ] ZX_INFO_BTI
